config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events

  get   'user/edit',           to: 'user#edit',             as: :user
  put   'user/edit',           to: 'user#update'

  get   'room/:uid',           to: 'room#index',            as: :room
  get   'channel/:uid/:id',    to: 'room#channel',          as: :channel
  post  'channel/:uid/:id',    to: 'room#create_channel',   as: :create_channel
  post  'message',             to: 'messages#create',       as: :messages
  post  'members/:event_id',   to: 'members#show',          as: :members
  post  'events/new',          to: 'events#new',            as: :home_new

  #OmniAuth Routes
  get '/auth/:provider/callback', to: 'oauth#callback', as: 'oauth_callback'
  get '/auth/failure', to: 'oauth#failure', as: 'oauth_failure'

  root to: 'index#home'
end

app/controllers/room_controller.rb
class RoomController < ApplicationController
  before_action :authenticate_user!

  def index
    @event = Event.find_by(uid: params[:uid])

    #TODO: If not event redirect 404
    @member = Member.find_by(event: @event, user: current_user)
    if @member.blank?
      @member = @event.members.create(user: current_user, role: :member)
      @member.channels << @event.channels.where(name: "General")
    end

    @message = Message.new
  end

  def channel
    @event = Event.find_by(uid: params[:uid])

    @member = Member.find_by(user: current_user, event: @event)
    unless @member.blank?
      @channel = @member.channels.find(params[:id])
    end

    @message = Message.new(member: @member, channel: @channel)
  end

  def create_channel
    event = Event.find_by(uid: params[:uid])

    host_member = Member.find_by(event: event, user: current_user)
    guest_member = Member.find_by(event: event, id: params[:id])

    return redirect_to room_url(event.uid), alert: 'Invalid member id.' if host_member.blank? || guest_member.blank?
    return redirect_to room_url(event.uid), alert: 'Cannot create a channel with yourself.' if host_member == guest_member

    channels = host_member.channels.joins(:members).where(members: {id: guest_member.id})
    unless channels.blank? || channels.count < 1
      channels.each do |channel|
        return redirect_to room_url(event.uid), alert: 'Channel is alredy created.' if channel.members.count == 2
      end
    end

    channel = Channel.create(event: event)
    channel.members << Member.find_by(event: event, user: current_user)
    channel.members << Member.find_by(event: event, id: params[:id])
    redirect_to room_url(event.uid), notice: 'Channel was successfully created.'

  end
end

app/helpers/room_helper.rb
module RoomHelper
end

app/views/room/_channel_info.html.slim
.contact-container
  .avatar-container
    = image_tag 'icon_alt.png'
  .info-container
    - aux_member = @channel.members.select { |member| member[:id] != @member.id }[0]
    .name = @channel.name || aux_member.first_name || aux_member.username
    - if @channel.members.size > 2
      .members = @channel.members.map {|member| "#{member.first_name || member.username}"}.join(', ')

app/views/room/_channels.html.slim
= link_to channel_path(channel.event.uid , channel.id), class: "contact-container", method: :get, remote: true
  .avatar-container
    - aux_member = channel.members.select { |member| member[:id] != @member.id }[0]
    - if channel.members.count > 2
      = image_tag 'icon_alt.png'
    - else
      = image_tag aux_member.avatar
  .contact-main.channel data-channel="#{channel.id}"
    .contact
      .name = channel.name || aux_member.first_name || aux_member.username
      .last-msg
        - last_msg = channel.messages.last
        - unless last_msg.blank?
          = "#{last_msg.member == @member ? 'me' : last_msg.member.first_name || last_msg.member.username}: #{last_msg.body}"

    .date-container
      .date = last_msg.time unless channel.messages.blank?
      //.count 1

app/views/room/_members.html.slim
#members_modal.modal.bottom-sheet
  .modal-content.container
    h4 Miembros
    .collection
      - unless @event.members.blank?
        - @event.members.each do |member|
          - unless member.user_id == current_user.id
            = link_to create_channel_path(@event.uid, member.id), class: "collection-item avatar", method: "post"
              = image_tag member.user.avatar.url, class: 'circle'
              .title = "#{member.first_name} #{member.last_name}"
              p = member.email
              span class="#{member.role}" = member.role

  .modal-footer
    a class="modal-close waves-effect waves-green btn-flat" Ok

app/views/room/_messages.html.slim
- @channel.messages.each do |message|
  div class="msg #{message.member == @member ? 'me' : 'you'}"
    - unless message.member == @member
      div class="writter type-#{message.member.id % 5}" = message.member.user.first_name || message.member.user.username
    .content
      = message.body
      span = message.created_at.strftime("%H:%M")

app/views/room/_send_box.html.slim
= form_with model: @message, class: 'send_box' do |f|
  = f.text_field :body, placeholder: "Write a message here", id: "msg-body", required: true, autocomplete: 'off'

  = hidden_field :message, :channel_id
  = hidden_field :message, :member_id

  = f.button :button, type: :submit, class: 'send'
    i.material-icons send

app/views/room/channel.js.erb
$('#chatter-box').html('<%= render j "messages" %>').attr('data-channel', '<%= @channel.id %>');
$('#channel_info').html('<%= render j "channel_info" %>');
$('#send_box').html('<%= render j "send_box" %>');

$('.chatter-box').addClass('active')
$('.chatter-box').scrollTop($('.chatter-box')[0].scrollHeight);
$('#msg-body').focus();

$('.contact-main.channel').parent().removeClass('active');
$('.contact-main.channel[data-channel="<%= @channel.id %>"]').parent().addClass('active');
$('.contact-main.channel[data-channel="<%= @channel.id %>"] .count ').remove();

app/views/room/index.html.slim
.room style="background:url('#{image_url("networking_2.jpg")}') repeat center center;"
  .chatter-container.container
    .options.row
      #member_info.profile data-member="#{current_user.id}"
        .contact-container
          .avatar-container
            = image_tag 'icon_alt.png'
          /.dropdown
          /  a href="#"
          /    i.material-icons more_vert
      #channel_info.contact
    .chatter-main
      .contacts
        .search_box-container
          .search_box
            i.material-icons search
            input.validate type="text" placeholder="Search"
        .scrolleable
          - @member.channels.each do |channel|
            = render partial: 'channels', locals: {channel: channel}
          a.contact-container.new.modal-trigger href="#members_modal"
            span Crea una nueva conversación
            button.btn-floating.waves-effect.waves-light
              i.material-icons add
      .chatter
        .chatter-box
          .starter
          #chatter-box data-channel=""
          .starter
        .message-form#send_box

= render partial: 'members'