config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events

  get   'user/edit',           to: 'user#edit',             as: :user
  put   'user/edit',           to: 'user#update'

  get   'room/:uid',           to: 'room#index',            as: :room
  get   'channel/:uid/:id',    to: 'room#channel',          as: :channel
  post  'channel/:uid/:id',    to: 'room#create_channel',   as: :create_channel
  post  'message',             to: 'messages#create',       as: :messages
  post  'members/:event_id',   to: 'members#show',          as: :members
  post  'events/new',          to: 'events#new',            as: :home_new

  #OmniAuth Routes
  get '/auth/:provider/callback', to: 'oauth#callback', as: 'oauth_callback'
  get '/auth/failure', to: 'oauth#failure', as: 'oauth_failure'

  root to: 'index#home'
end

app/views/shared/_alerts.html.slim
- if notice
  javascript:
    toastr.success('#{notice}');

- if alert
  javascript:
    toastr.error('#{alert}');

app/views/shared/_footer.html.slim
footer.page-footer
  .container
    .row
      .col.l6.s12
        h5 Meet
        = image_tag 'utn_logo.png'
        /p.grey-text.text-lighten-4 You can use rows and columns here to organize your footer content.
      .col.l4.offset-l2.s12
        h5 Info
        ul
          li
            a href="https://www.linkedin.com/in/gonzalograssi/" Gonzalo Grassi
          li
            a href="http://www1.frm.utn.edu.ar/tsprogramacion/index.html" TSP
          li
            a href="https://rubyonrails.org/" RoR
  .footer-copyright
    .container
      .row
        .col.l6.s12 © 2018 UTN-FRM
        .col.l4.offset-l2.s12 TSP

app/views/shared/_header.slim
header
  nav
    .nav-wrapper.container
      a.brand-logo href==root_url style="outline:none"
        = image_tag 'logo.png', class: 'logo'

      a.sidenav-trigger href="#" data-target="mobile-demo"
        i.material-icons menu

      ul.right.hide-on-med-and-down
        - if current_user
          li
            a.dropdown-trigger href="#!" data-target="dropdown1"
              = current_user.username
              i.material-icons.right arrow_drop_down
        - else
          li
            = link_to "Crear Usuario", new_user_registration_path
          li
            = link_to "Iniciar Sesion", new_user_session_path

      ul#dropdown1.dropdown-content
        li
          = link_to "Mis Eventos", events_path
        li
          = link_to "Editar Perfil", user_path
        li
          = link_to "Cambiar Contraseña", edit_user_registration_path
        li.divider
        li
          = link_to "Cerrar Sesion", destroy_user_session_path, method: :delete

  ul#mobile-demo.sidenav
    - if current_user
      li
        = link_to "Mis Eventos", events_path
      li
        = link_to "Editar Perfil", edit_user_registration_path
      li.divider
      li
        = link_to "Cerrar Sesion", destroy_user_session_path, method: :delete
    - else
      li
        = link_to "Inicio", root_url
      li.divider
      li
        = link_to "Iniciar Sesion", new_user_session_path
      li.divider
      li
        = link_to "Registrarme", new_user_registration_path