config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events

  get   'user/edit',           to: 'user#edit',             as: :user
  put   'user/edit',           to: 'user#update'

  get   'room/:uid',           to: 'room#index',            as: :room
  get   'channel/:uid/:id',    to: 'room#channel',          as: :channel
  post  'channel/:uid/:id',    to: 'room#create_channel',   as: :create_channel
  post  'message',             to: 'messages#create',       as: :messages
  post  'members/:event_id',   to: 'members#show',          as: :members
  post  'events/new',          to: 'events#new',            as: :home_new

  #OmniAuth Routes
  get '/auth/:provider/callback', to: 'oauth#callback', as: 'oauth_callback'
  get '/auth/failure', to: 'oauth#failure', as: 'oauth_failure'

  root to: 'index#home'
end

app/models/event.rb
class Event < ApplicationRecord
  require "base64"

  before_create :generate_uid
  belongs_to :owner, class_name: 'User'
  has_many :members
  has_many :channels

  has_attached_file :image, styles: { medium: "300x300>" }, default_url: ActionController::Base.helpers.asset_path('event-default.jpg')
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  validates :name, presence: true
  validates :start_at, presence: true

  attr_accessor :date
  attr_accessor :time

  private
    after_find do |event|
      self.date = event.created_at.strftime('%b %d, %Y');
      self.time = event.created_at.strftime('%I:%M %p');
    end

    def generate_uid
      date = Time.now.to_i
      self.uid = Base64.encode64(date.to_s)[0..-4]
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    memberships = Member.where(user_id: current_user.id)

    @events = []
    memberships.each do |member|
      @events.push(member.event)
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    if home_params.blank?
      @event = Event.new
    else
      @event = Event.new(home_params)
    end
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    @event.owner = current_user
    @event.members << Member.new(user: current_user, role: :owner)
    @event.channels << Channel.new(name: 'General', members: @event.members)

    respond_to do |format|
      if @event.save
        format.html { redirect_to events_path, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to events_path, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.members.destroy_all
    @event.channels.destroy_all
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      sanitaize_params = params.require(:event).permit(:date, :time, :start_at, :name, :description, :image)
      sanitaize_params[:start_at] = DateTime.parse(sanitaize_params[:date] + ' ' + sanitaize_params[:time]) unless sanitaize_params[:date].blank? && sanitaize_params[:time].blank?
      return sanitaize_params
    end

    def home_params
      unless params[:event].blank?
        params.require(:event).permit(:date, :time)
      end
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.slim
.container.form-section
  = simple_form_for(@event) do |f|
    = f.error_notification
    = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

    .form-inputs
      = f.input :date, required: true, input_html: {class: "datepicker"}

      = f.input :time, required: true, input_html: {class: "timepicker"}

      = f.input :name

      = f.input :description

      = f.input :image, as: :file

    .form-actions
      = f.button :submit

app/views/events/edit.html.slim
.container
  h3 Editing Event

  = render 'form', event: @event

app/views/events/index.html.slim
.container
  title.container
    h3 Events

  .row.card-container
    - @events.each do |event|
      .col.s12.m6.l4
        .card
          .card-image style="background:url('#{event.image.url(:medium)}') no-repeat center center;"
            = image_tag event.image.url(:medium)

            .btn-floating.halfway-fab
              - if event.owner.id == current_user.id
                = link_to event, class: "btn-floating waves-effect waves-light modal-trigger", method: :delete, data: {confirm: "Estas seguro de eliminar el evento?"} 
                  i.material-icons delete

              - if event.owner.id == current_user.id
                = link_to members_path(event.id), class: "btn-floating waves-effect waves-light modal-trigger", method: :post, remote: true
                  i.material-icons people

              - if event.owner.id == current_user.id
                a.btn-floating.waves-effect.waves-light href == edit_event_path(event)
                  i.material-icons edit

              a.btn-floating.waves-effect.waves-light href == room_url(event.uid)
                i.material-icons arrow_forward
          .card-content
            .card-date
              .date-month
                = event.created_at.strftime('%b.').upcase
              .date-day
                = event.created_at.strftime('%d').upcase
            .card-title
              span = event.name
              p = event.description

    .col.s12.m4
      a.btn-floating.btn-large.waves-effect.waves-light href == new_event_path
        i.material-icons add

#members_modal.modal.bottom-sheet
  .modal-content

  .modal-footer
    a href="#!" class="modal-close waves-effect waves-green btn-flat" Ok

app/views/events/new.html.slim
.container
  h3 New Event

  = render 'form', event: @event

app/views/events/show.html.slim
.room style="background:url('#{image_url("networking_2.jpg")}') repeat center center;"
  .chatter-container.container
    .options.row
      .profile
        .contact-container
          .avatar-container
            = image_tag 'icon_alt.png'
          .dropdown
            a href="#"
              i.material-icons more_vert
      .contact
        .contact-container
          .avatar-container
            = image_tag 'icon_alt.png'
          .info-container
            .name General
            .members Amigo Imaginario, Edu, Tú
    .chatter-main
      .contacts
        .search_box-container
          .search_box
            i.material-icons search
            input.validate type="text" placeholder="Search"
        .scrolleable
          - 10.times do
            .contact-container
              .avatar-container
                = image_tag 'icon_alt.png'
              .contact-main
                .contact
                  .name Gonzalo Grassi
                  .last-msg Gon: Hola!
                .date-container
                  .date 15:22
      .chatter
        .chatter-box
          .starter
          .msg.you
            .writter Amigo Imaginario
            .content
              | Hola!
              span 12:43
          .msg.you
            | Como estas?
            span 12:44
          .msg.me
            | Hola, todo bien
            span 12:50
          .msg.you
            .writter Edu
            | Pana, ya tengo ganas de perder en el metegol otra vez.
            span 12:57
        .message-form
          .send_box
            input.validate type="text" placeholder="Write a message here"
            .send
             i.material-icons send